### ISSUE TITLE
textgroup urls broken

### ISSUE THREAD

**Issue by balmas** [PerseusDL/perseus_catalog#45]
The urls for the text groups aren't working anymore
e.g.

http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0538

**Comment by annakrohn** [comment]
Fixed in commit 4b585a9cd9969ff285849a7eee8168eca4b9cc90.  Will close when I get it updated on the server.

**Comment by annakrohn** [comment]
fully fixed in commit e338e8da6f1ed2a4cd99c0f17fdd1b2a3c63bb3d.  Live on site.
