### ISSUE TITLE
distinct fields of activity need to be cleaned up

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/perseus_catalog#60]
Here's the distinct list of activity fields in the MADS records; it would be great to standardize these and then fix them, programmatically, in the MADS

1. Epigrammatist
2. 
3. Historian
4. Hagiographer
5. Monk
6. Comic Poet
7. Jurist
8. Epic Poet
9. Philosopher
10. Agricultural Writer
11. Agricultural Author
12. Grammarian
13. Latin Poet
14. Tragic Poet
15. Bishop
16. Theologian
17. Orator
18. Panegyrist
19. Saint
20. Tactician
21. Military Author
22. Musician
23. Abbot
24. Poet
25. King
26. Consul
27. Commentator
28. Patriarch
29. Chronographer
30. Epic poet   
31. Presocratic
32. Politician
33. Bucolic Poet
34. Humanist
35. Poetess
36. Epistolary
37. Epicurean
38. Lyric Poet
39. Geographer
40. Cynic
41. Phiolosopher
42. Elegist
43. Ethnographer
44. Rhetorician
45. Sophist
46. Biographer
47. Astrologer
48. Mimograph
49. Physician
50. Stoic
51. Emperor
52. Pope
53. Chronicler
54. Pythagorean
55. Mythographer
56. Antiquarian
57. Attic Orator
58. Logographer
59. General
60. Critic
61. Rhetor
62. Fictitious Author
63. Tragedian
64. Editor
65. Philologist
66. Dithyrambic Poet
67. Dithyramb
68. Apologist
69. Satirist
70. Prophet
71. Franciscan
72. Paradoxographer
73. Deacon
74. Neoplatonist
75. Surveyor
76. Agrarian Writer
77. Dramatist
78. Mathematician
79. Astronomer
80. Prescoratic
81. Technical Author
82. lyric poet
83. iambic poet
84. mimiamb
85. Peripatetic
86. Iambograph
87. Iambic Poet
88. Iambography
89. Philolosopher
90. Doxographer
91. Metrist
92. Metrician
93. Erotic Poet
94. Novelist
95. Tribune
96. Pre-Socratic
97. Priest
98. Miscellanist
99. Horticulturist
100. Veterinarian
101. Fabulist
102. Hymnodist
103. Presbyter
104. Epigrapher
105. Annalist
106. Fictitous Author
107. Archibishop
108. Church Father
109. Mathemetician
110. historian
111. rhetor
112. Travel Writer
113. Tragic poet
114. Tyrant
115. Hstorian
116. comic poet
117. Comedian
118. Playwright
119. epigrammatist
120. orator
121. Medical author
122. Religious Author
123. Pharmacological writer
124. Medical Author
125. Church synod
126. seven sages
127. septem sapientes
128. Church father
129. Statesman
130. Septem Sapientes
131. Seven Sages
132. Architectural Author
133. Encyclopedist
134. Platonist
135. poet
136. Iambographer
137. cardinal
138. astronomer
139. saint
140. bishop
141. epigrammatiker
142. Fictious Author
143. emperor
144. sophist
145. rhetorician
146. grammarian
147. Comic poet
148. Pseudo-Author
149. dithyrambic poet
150. Geometer
151. Physicist
152. Soldier
153. Neo-Pythagorean
154. epic poet
155. Pilgrim
156. Anonymous Author
157. Atthidographer
158. Presocratic
159.     
160. Translator
161. Pseudo Author
162. Military author
163. Scriptor Eroticus
164. Erotic Author
165. Statuary
166. Compiler
167. Military Writer
168. Greek Poet
169. Didactic Poet
170. Lyric Muse
171. Greek language -
172. Lexicographer
173. Neo-Latin Poet
174. Lyricist
175. Archbishop
176. Anonymous Authors
177. Historiographer
178. Parodist
179. Author of Parodies
180. Author of Togatae
181. Textbook author
182. Senator
183. Neoplatonism 
184. Architect
185. Musical Author
186. Scientist
187. Martyr
188. Pharoah
189. Author
190. Logoographer
191. Natural Historian
192. Natural Philosopher
193. Biologist
194. Botanist
195. Pharmacologist
196. Scholar
197. Antipope
198. Cartographer
199. Physician?
200. Medical Writer
201. Magician
202. Magian
203. Travel writer
204. Old Comedy
205. Courtier
206. Renaissance Author
207. Stoic?
208. philosopher
209. Middle Platonist
210. Epistolographer
211. Attributed Author
212. Skeptic
213. Moralist
214. Scribe
215. theologian
216. Lyric poet
217. Epigrammaticus
218. Latin  Poet
219. Dichter der Alten Komödie
220. Hymnist
221. consul
222. Anonymous Epic Author
223. Iambic poet
224. Aulete
225. tragic poet
226. Culinary Author
227. Gastronomical Poet
228. Anonymous Commentator
229. Attributed author
230. Citharist
231. Metropolitan
232. Gnomic Poet
233. Literary Critic
234. Anthologist
235. Christian Poet
236. Mechanic
237. Engineer
238. Male
239. Magistrate
240. Librarian
241. Polymath
242. Byzantine Poet
243. Metic
244. Veterinary Author
245. Explorer
246. Nun
247. Medicine Islamic philosophy -
248. Paeanist
249. Governor
250. Mimographer
251. Strategist
252. Musical theoretician
253. Hippiatrica
254. Preacher
255. Egyptian priest
256. Epic poet
257. Gastronomic poet
258. Archaist
259. fabulist
260. Cardinal
261. Erotic Writer
262. Musical author
263. Musical Theoretician
264. philological scholar
265. historiographer
266. iambographer
267. erotic writer
268. Mathmetician
269. Elegiac Poet
270. Professor
271. Lyic Poet
272. Grammariann
273. commentator
274. Contested Author
275. Architectural Writer
276. mathematician
277. mathemetician
278. geographer
279. mythographer
280. Empress
281. Astrologist
282. Ethicist
283. hagiographer
284. Diplomat
285. Anonymous Textgroup
286. Glossator
287. Marytr
288. Scholiast
289. Polemicist
290. Military Theoritician
291. physician
292. Culinary Writer
293. Phiologist
294. Peripatetic 
295. epigrammtiker
296. Dream interpreter
297. Dietician
298. panegyrist
299. Peripatetics
300. biographer
301. Author of fables
302. Epistolary Poet
303. Philoslopher

**Comment by AlisonBabeu** [comment]
Hi @cwulfman I've created a spreadsheet that maps the values that need to be replaced here, I hope this is what you needed:
https://docs.google.com/spreadsheets/d/1Ufzd6TdZOgCXiIXZXGWJZDnOdv7cdDipAR-2483j2iU/edit#gid=0

**Comment by cwulfman** [comment]
Don’t have permission to see this, alas…

On Jan 22, 2018, at 1:01 PM, Alison Babeu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @cwulfman<https://github.com/cwulfman> I've created a spreadsheet that maps the values that need to be replaced here, I hope this is what you needed:
https://docs.google.com/spreadsheets/d/1Ufzd6TdZOgCXiIXZXGWJZDnOdv7cdDipAR-2483j2iU/edit#gid=0

**Comment by AlisonBabeu** [comment]
You should have it now.

**Comment by cwulfman** [comment]
Thanks! What is that 'keep' column?

**Comment by AlisonBabeu** [comment]
I just used that column to quickly be able to add a Yes or No to sort the list into those Activities that had correct names and those we wanted to rename.

**Comment by cwulfman** [comment]
Got it. I'll apply the changes now.

**Comment by cwulfman** [comment]
@AlisonBabeu I applied the changes and committed them to the development branch. Please take a look; if they pass muster, I'll merge it into master.

**Comment by AlisonBabeu** [comment]
I took a look and it seems the changes are fine. Thanks!
