### ISSUE TITLE
Duplicate lists of works continues under authors

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/perseus_catalog#63]
This seems to be a fairly widespread problem, although I've only currently documented it for Latin authors such as [Cicero](http://174.138.78.35:8080/exist/apps/PerseusCatalog/authors.html?id=urn:cite:perseus:author.364.1). 

For example, the work "Letters to Brutus" appears 8 times in this list (all with the same work CTS-URN (urn:cts:latinLit:phi0474.phi059), and clicking on the any of these 8 links takes you to the same list of [versions](http://174.138.78.35:8080/exist/apps/PerseusCatalog/works.html?id=urn:cts:latinLit:phi0474.phi059).

**Comment by AlisonBabeu** [comment]
And with Greek as well, see Euripides (http://174.138.78.35:8080/exist/apps/PerseusCatalog/authors.html?id=urn:cite:perseus:author.601.1)

**Comment by cwulfman** [comment]
This was a bug in the function catalog:works-by(). Fixed now. If it looks good to you, please close the ticket.

**Comment by AlisonBabeu** [comment]
This look like it has been fixed. Love the new styling too @cwulfman btw.
