### ISSUE TITLE
Authority records delinked in list of authors-author records also missing

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/perseus_catalog#64]
I stumbled upon this issue while I started to browse authors by Activity List. 

For example, the list of [Annalists](http://174.138.78.35:8080/exist/apps/PerseusCatalog/browse.html?activity=Annalist) has a number of unlinked records such Atticus and Hortensius Hortalus.

![image](https://user-images.githubusercontent.com/4663626/35524845-d464f038-04f0-11e8-980b-ca3bc40ed454.png)

I also can't find authority records for these authors among many others as well when I go through the entire authors list, even though they are listed there. I haven't found any pattern as yet to why records might be missing.

**Comment by cwulfman** [comment]
@AlisonBabeu There was some index corruption. I fixed it, and everyone seems to be showing up again. Check it out, and close the ticket if you don't find problems.

**Comment by AlisonBabeu** [comment]
This definitely appears to have been fixed. Thanks!
