### ISSUE TITLE
Further data from MODS records to include in version records 

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/perseus_catalog#65]
1) Page level data when it is available
For example for the following [version](http://174.138.78.35:8080/exist/apps/PerseusCatalog/versions.html?id=urn:cts:latinLit:phi0474.phi040.opp-lat1) the [current MODS record](http://174.138.78.35:8080/exist/apps/PerseusCatalog/versions.html?id=urn:cts:latinLit:phi0474.phi040.opp-lat1) also includes the following: 
```xml
<mods:part xmlns="http://www.loc.gov/mods/v3">
<mods:extent unit=”pages”>
    <mods:start>314</mods:start>
    <mods:end>382</mods:end>
</mods:extent>
</mods:part>
```
2) Indicate the language of the version/translation (I know lat-1 perhaps seems obvious)

3) Indicate which links are to individual page levels, perhaps for the first "link" change label to "page level link" or something like that?

**Comment by cwulfman** [comment]
@AlisonBabeu  Updated to version 0.0.12 -- now displays languages and extents (albeit not elegantly).

Also does a better job of grouping and sorting some of the lists.

**Comment by cwulfman** [comment]
Could you please close this issue as well, @AlisonBabeu ?
