### ISSUE TITLE
Full record for multi-volume MODS records missing data

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/perseus_catalog#66]
When looking at a sample [version](http://174.138.78.35:8080/exist/apps/PerseusCatalog/versions.html?id=urn:cts:greekLit:tlg0003.tlg001.opp-lat2) for Thucydides that has four volumes, the full record only contains information for the first volume, the bottom of the screen simply shows a list with no links to the records.

constituents
    Histories : Volumen Primum
    Histories : Volumen Secundum
    Histories : Volumen Tertium
    Histories : Volumen Quartum

**Comment by cwulfman** [comment]
@AlisonBabeu I've moved this issue to the new issue-board at agile: https://github.com/agile-humanities/perseus_catalog/issues/1, so I'm going to close it here.

**Comment by cwulfman** [comment]
Actually, @AlisonBabeu , I *can't* close this issue because I don't have the necessary permissions. Could you do that, please?

**Comment by AlisonBabeu** [comment]
Never......! Just kidding!
